# Install the apt prerequisites
# addons:
#   apt:
#     packages:
#       - python-pygments

language: go

go:
  - master

install:

# Build the website
install:
  - go get github.com/spf13/hugo
  # Clean and don't fail
  #- rm -rf public || exit 0
  - ./gh-pages.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  # target_branch: gh-pages
  fqdn: michel.frichet.org
  email: deploy@frichet.org
  name: Deployer
  on:
    branch: master
