# Install the apt prerequisites
# addons:
#   apt:
#     packages:
#       - python-pygments

language: go

go:
  - master

sudo: false

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - DEP_VERSION="0.3.2"
    - GIT_NAME="Deployer"
    - GIT_EMAIL="deployer@frichet.org"
    - SOURCE_DIR="public"
    # - DEPLOY_BRANCH="source"

cache:
  directories:
    - $GOPATH/pkg/hugo

# before_install:
#   # Download the binary to bin folder in $GOPATH
#   - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
#   # Make the binary executable
#   - chmod +x $GOPATH/bin/dep
#   # OR - go get -u -v github.com/golang/dep/cmd/dep

install:
  # - dep ensure -vendor-only
  # - go install github.com/frichet/michel/vendor/github.com/gohugoio/hugo
  - go get -u -v -d github.com/gohugoio/hugo

script:
  - echo $SOURCE_DIR
  # Clean and don't fail
  - rm -rf $SOURCE_DIR || exit 0
  # Build the website
  - hugo -d $SOURCE_DIR

after_success:
  - echo "michel.frichet.org" > ./$SOURCE_DIR/CNAME
  # - ./scripts/deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  # target_branch: gh-pages
  fqdn: michel.frichet.org
  email: deploy@frichet.org
  name: Deployer
  on:
    branch: master
