# Install the apt prerequisites
addons:
  apt:
    packages:
      # - golang
      - python-pygments

# language: go

# go:
#   - master

sudo: false

git:
  depth: 10
  submodules: true

branches:
  only:
    - master

env:
  global:
    - GIT_NAME="Deployer"
    - GIT_EMAIL="deployer@frichet.org"
    - SOURCE_DIR="public"

# cache:
#   directories:
#     - $GOPATH/src
#     - $GOPATH/pkg
#     # - $GOPATH/pkg/hugo

before_install:
  - which go
  - echo $GOPATH

install:
  - go get github.com/gohugoio/hugo

script:
  # Clean and don't fail
  - rm -rf $SOURCE_DIR || exit 0
  # Build the website
  - hugo # -d $SOURCE_DIR

after_success:
  - echo "michel.frichet.org" > ./$SOURCE_DIR/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  # target_branch: gh-pages
  fqdn: michel.frichet.org
  email: deploy@frichet.org
  name: Deployer
  on:
    branch: master
