# Install the apt prerequisites
# addons:
#   apt:
#     packages:
#       - python-pygments

language: go

go:
  - master

sudo: false

git:
  depth: 10

# branches:
#   only:
#     - master

# env:
#   global:
#     - SOURCE_DIR="public"
#     - BUILD_BRANCH="source"
#     - DEPLOY_BRANCH="master"

install:
  - go get github.com/spf13/hugo
  # # Clean and don't fail
  # - rm -rf public || exit 0

# Build the website (gh-pages.sh)
script: hugo # -d public

after_success:
  - echo michel.frichet.org >> public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  # target_branch: gh-pages
  fqdn: michel.frichet.org
  email: deploy@frichet.org
  name: Deployer
  on:
    branch: master
