# Install the apt prerequisites
# addons:
#   apt:
#     packages:
#       - python-pygments

language: go

go:
  - master

sudo: false

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - GIT_NAME="Deployer"
    - GIT_EMAIL="deployer@frichet.org"
    - SOURCE_DIR="public"
    # - DEPLOY_BRANCH="source"

cache:
  directories:
    - $GOPATH/pkg/hugo

install:
  - go get -u -v -d github.com/gohugoio/hugo

script:
  - echo $SOURCE_DIR
  # Clean and don't fail
  - rm -rf $SOURCE_DIR || exit 0
  # Build the website
  - hugo -d $SOURCE_DIR

after_success:
  - echo "michel.frichet.org" > ./$SOURCE_DIR/CNAME
  # - ./scripts/deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  # target_branch: gh-pages
  fqdn: michel.frichet.org
  email: deploy@frichet.org
  name: Deployer
  on:
    branch: master
