language: go

go:
  - 1.8

sudo: false

git:
  depth: 10
  submodules: true

branches:
  only:
    - master

env:
  global:
    - GIT_NAME="Deployer"
    - GIT_EMAIL="deployer@frichet.org"
    - PUBLISH_DIR="public"

cache:
  directories:
    - $GOPATH/src/github.com/gohugoio
    - $GOPATH/pkg/hugo

install:
  - go get github.com/gohugoio/hugo

script:
  # Clean and don't fail
  - rm -rf "$PUBLISH_DIR" || exit 0
  # Build the website
  - hugo -d "$PUBLISH_DIR"

after_success:
  - echo "michel.frichet.org" > "./$PUBLISH_DIR/CNAME"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: $PUBLISH_DIR
  # target_branch: gh-pages
  fqdn: michel.frichet.org
  email: deploy@frichet.org
  name: Deployer
  on:
    branch: master
