publishDir = "public"
# baseURL = "https://frichet.github.io/michel"
baseURL = "//michel.frichet.org"
languageCode = "fr-fr"
title = "Michel Frichet"
theme = "ananke"
# theme = "gohugo-theme-ananke"

# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 25
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "V2"
  facebook = ""
  twitter = "" # https://twitter.com/GoHugoIO
  instagram = ""
  youtube = ""
  github = "https://github.com/frichet/michel"
  linkedin = "https://www.linkedin.com/in/michel-frichet-814593b/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  featured_image = "/images/featured.jpg"
  # recent_posts_number = 10
  body_classes = "avenir bg-near-white"
  read_more_copy = 'Voir plus'

# [Languages]
#   [Languages.en]
#     weight = 1
#     title = "English"
#   [Languages.en.blackfriday]
#     angledQuotes = false

#   [Languages.fr]
#     weight = 2
#     title = "Français"
#   [Languages.fr.Taxonomies]
#     plaque = "plaques"

[params.navigation]
help  = "Aide"

[Languages.fr]
# title = "Mon blog"
# weight = 1
# [Languages.fr.params]
# linkedin = "lien-francais"

# [Languages]
# [Languages.en]
# # title = "My blog"
# # weight = 2
# # [Languages.en.params]
# # linkedin = "english-link"
# [Languages.fr.navigation]
# help  = "Help"
