baseURL = "//michel.frichet.org"
languageCode = "fr-fr"
title = "Michel Frichet"
theme = "ananke"

publishDir = "public"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 25
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Forme, couleur, matière et lumière sont indissociables."
  facebook = ""
  twitter = "" # https://twitter.com/GoHugoIO
  instagram = ""
  youtube = ""
  github = "https://github.com/frichet/michel"
  linkedin = "https://www.linkedin.com/in/michel-frichet-814593b/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-gray"
  featured_image = "/images/featured.jpg"
  # recent_posts_number = 10
  # body_classes = "avenir bg-near-white"
  read_more_copy = 'Voir plus'

[[menu.main]]
  identifier = "collection"
  name = "Collections"
  weight = 2
  url = '/collection/'

[[menu.main]]
  identifier = "projet"
  name = "Projets"
  weight = 2
  url = '/projet/'

[[menu.main]]
  identifier = "a-propos"
  name = "À propos"
  # pre = "<i class='fa fa-plus'></i>"
  weight = 1
  url = "/a-propos/"

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  # pre = "<i class='fa fa-envelope'></i>"
  weight = 0
  url = "/contact/"

# [params.navigation]
# about  = "À propos"

# [Languages]

#   [Languages.fr]
#     weight = 1
#     title = "Français"
#   # [Languages.fr.params]
#   #   linkedin = "lien-francais"
#   [Languages.fr.Taxonomies]
#     collection = "collections"
#     projet = "projets"
#   [Languages.fr.navigation]
#     help  = "Help"

#   [Languages.en]
#     weight = 2
#     title = "English"
#   # [Languages.en.params]
#   #   linkedin = "english-link"
#   [Languages.en.blackfriday]
#     angledQuotes = false
#   [Languages.en.navigation]
#     help  = "Help"
